### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by NutanNiraula** [mikepham1011/nimble-survey-app-ios#6]
The survey api should be capable of providing more data than you have currently displayed. It would be nice if we could paginate those data by some user input. What do you think?

**Comment by mikepham1011** [comment]
Hi @NutanNiraula, I think there is already a pagination mechanism to help user get more data. You can do it by scrolling the navigation indicator list down to trigger the load more action. Please help me check again if you can perform the load more actions.

**Comment by mikepham1011** [comment]
By the way how much data do we have in total? So far I can load two pages of 10 items per page, and when I try to load the page 3 it is returning empty response, so it means there are max 20 items? is that correct?

**Comment by mikepham1011** [comment]
Per issue #5 point 3, I implemented the scrolling capability for the survey list and thus I already moved the logic of scrolling-to end-to load more from the navigation indicators list to the survey list scroll view itself. Now when you scroll horizontally and reach the last item, it will trigger a load more to get the next page data. It is implemented in 696a3ae.
